### ISSUE TITLE
Support python3.4.1

### ISSUE THREAD

**Issue by kitanin90** [hflabs/dadata-py#2]
dadata can be installed on python3.4? If so, what version?

**Comment by nalgeon** [comment]
Python 3.7+ only

**Comment by kitanin90** [comment]
support 3.6.12?

ср, 3 мар. 2021 г. в 15:26, Anton Zhiyanov <notifications@github.com>:

**Comment by kitanin90** [comment]
support 3.6.12 old version dadata?

ср, 3 мар. 2021 г. в 15:27, Vladimir <kitanin10266@gmail.com>:

**Comment by nalgeon** [comment]
Unfortunately, we do not plan to support older versions of Python.
