### ISSUE TITLE
import does not work

### ISSUE THREAD

**Issue by qwerty1661** [hflabs/dadata-py#3]
I create virualenv with python 3.8.5
do pip install dadata
receive **Successfully installed dadata-20.7.0**
go into python shell
do **from dadata import Dadata**
receive **ImportError: cannot import name 'Dadata' from partially initialized module 'dadata' (most likely due to a circular import)**

**Comment by elchako** [comment]
try command  **pip3 install dadata**

**Comment by nalgeon** [comment]
Your package is probably called 'dadata', which creates a circular import. Rename it.

**Comment by AlexGCPrint** [comment]
ImportError: cannot import name 'Dadata' from 'dadata'  🤷‍♂️
