### ISSUE TITLE
Can't import Dadata from dadata

### ISSUE THREAD

**Issue by BogovAlex** [hflabs/dadata-py#6]
I create virtualenv with python 3.7.9

Install package:
`pip install dadata`

Try to Import package:
`from dadata import Dadata`

Importing produce error:
`Traceback (most recent call last):
  File "dadata.py", line 1, in <module>
    from dadata import Dadata
  File "C:\dev_python\retailCRM_script\dadata.py", line 1, in <module>
    from dadata import Dadata
ImportError: cannot import name 'Dadata' from 'dadata' (C:\dev_python\retailCRM_script\dadata.py)`

**Comment by BogovAlex** [comment]
Here is `pip freeze` output:

anyio==3.4.0
attrs==21.2.0
certifi==2021.10.8
charset-normalizer==2.0.9
coverage==6.2
dadata==21.10.1
furl==2.1.3
h11==0.12.0
httpcore==0.14.3
httpx==0.21.1
idna==3.3
importlib-metadata==4.8.2
importlib-resources==5.4.0
jsonschema==4.2.1
multidimensional-urlencode==0.0.4
nose==1.3.7
orderedmultidict==1.0.1
pook==1.0.2
pyrsistent==0.18.0
requests==2.26.0
retailcrm==5.1.2
rfc3986==1.5.0
six==1.16.0
sniffio==1.2.0
typing_extensions==4.0.1
urllib3==1.26.7
xmltodict==0.12.0
zipp==3.6.0

**Comment by nalgeon** [comment]
Rename your `dadata.py` into something different. It conflicts with the package name.
